### PR TITLE
Lec 2

### PR DESCRIPTION
**Pull request by wenhuizhang**
conversation server in C, I am testing the Java version, request a push later tonight, thanks for your patience

### CODE REVIEW

**Comment by twood02** [comment]
this should be as simple as possible, so don't have a command line argument for client or server (it should always be server). It looks like you aren't using mode_flag for anything yet, but I suggest you just remove it and the option entirely.

I wasn't going to have you bother make a version of this in C because I think almost all the students will use java or python, but it doesn't hurt to have this.

**Comment by wenhuizhang** [comment]
Good evening , prof. Wood, sorry for the delay, the C version template is tested, and in good shape,  and all have to be changed is around line117, add personalized converting function, "msg = func(value)", and the result will be returned to the client.  Right now, client is receiving default msg as “Welcome, connected” no matter what "-v value” is specified in command line.

wenhuizhang [11:32 PM]
Usage: ./conv_server
 -s : 's' for run as server; default as server
 -c : 'c' for run as client; default as server
 -p : your port number
 -h : your server ip address
 -v : your value here

**Comment by wenhuizhang** [comment]
For Java version:

 *  Compilation:  javac convServer.java
 *  Execution:    java convServer port

For Python version:
 *  Execution:    python convServer.py port

**Comment by wenhuizhang** [comment]
Good evening Prof. Wood:

Sorry for replying late, just saw your comment above....it was sent to spam folder....

Just changed all into concise versions, and updated c version as well:

For C version:
-  Compilation: gcc -o conv_server conv_server.c 
-  Execution:  sudo ./conv_server portnum 

For Java version:
-  Compilation:  javac convServer.java
-  Execution:    java convServer portnum

For Python version:
-  Execution:    python convServer.py portnum

**Comment by wenhuizhang** [comment]
For parsing,

C version:
    could use "char \* strtok (char *restrict newstring, const char *restrict delimiters)" , note that strtok has to specify number of delimiters,  s[2] = " ", means "2" space in the string to be parsed. 

```
const char s[2] = " ";
char *token;
/* get the first token */
token = strtok(str, s);  
/* walk through other tokens */
while( token != NULL ) {
   printf( " %s\n", token )   
   token = strtok(NULL, s);
}

Ref: http://www.gnu.org/software/libc/manual/html_node/Finding-Tokens-in-a-String.html
```

Java version:
    could use "split" method as below:

```
String[] tokens = str.split("  ");
for(String s:tokens){
        System.out.println(s);
    }

Ref: http://javadevnotes.com/java-string-split-tutorial-and-examples 
```

Python version:
    could use split function as below:

```
mylist = inputString.split(" ")
for item in mylist:
    print item
```

**Pull request merged**
